src/blog/urls.py
from django.urls import path
from.views import PostListView, PostDetailView, like_view


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('detail/<slug>', PostDetailView.as_view(), name='detail'),
    path('like/<slug>/', like_view, name='like')
]

src/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('content', include('content.urls', namespace='content')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/payment/urls.py
from django.urls import path
from .views import PaymentView, CreateSubscriptionView, RetryInvoiceView, EnrollView, webhook

app_name = 'payment'

urlpatterns = [
    path('enroll/', EnrollView.as_view(), name='enroll'),
    path('enroll/<slug>', PaymentView.as_view(), name='payment'),
    path('create-subscription/', CreateSubscriptionView.as_view(), name='create-subscription'),
    path('retry-invoice/', RetryInvoiceView.as_view(), name='retry-invoice'),
    path('webhook/', webhook, name='webhook')
]

src/users/urls.py
from django.urls import path
from .views import UserDetailView, UserUpdateView, UserSubscriptionView, CancelSubscriptionView


app_name = 'users'

urlpatterns = [
    path('update/', UserUpdateView.as_view(), name='update'),
    path('<str:username>/', UserDetailView.as_view(), name='detail'),
    path("<str:username>/subscription/", UserSubscriptionView.as_view(), name='subscription'),
    path("<str:username>/subscription/cancel/", CancelSubscriptionView.as_view(), name='cancel-subscription')
]

src/users/models.py
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

class User(AbstractUser):
    
    name = CharField(_('Name Of User'), blank=True, max_length=200)
    stripe_customer_id = CharField(max_length=50)

    # username = None
    # email = models.EmailField(unique=True, max_length=255)
    # USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = []
    


    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

   

src/users/forms.py
from django.contrib.auth import forms 
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

from django import forms as dj_forms

from django.utils.translation import ugettext_lazy as _

from django.contrib.auth import get_user_model


User = get_user_model()

class CancelSubscriptionForm(dj_forms.Form):
    hidden = dj_forms.HiddenInput()

class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise ValidationError(self.error_messages["duplicate_username"])
  

src/users/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.views.generic import DetailView, UpdateView
from django.urls import reverse
from django.views.generic import FormView
import stripe

from .forms import CancelSubscriptionForm

User = get_user_model()

stripe.api_key = settings.STRIPE_SECRET_KEY

class CancelSubscriptionView(LoginRequiredMixin, FormView, DetailView):
    form_class = CancelSubscriptionForm

    def get_success_url(self):
        return reverse('users:detail', kwargs={'username': self.request.user.username})

    def form_valid(self, form):
        stripe.Subscription.delete(self.request.user.subscription.stripe_subscription_id)
        messages.success(self.request, 'You have successfully cancelled your subscription!')
        return super().form_valid(form)

class UserSubscriptionView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = 'users/user_subscription.html'



class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/user_detail.html'

    slug_field = "username"
    slug_url_kwarg = "username"

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["username"]

    template_name = 'users/user_form.html'

    def get_success_url(self):
        return reverse('users:detail', kwargs={'username': self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_invalid(self, form):
        return super().form_valid(form)

src/templates/users/user_detail.html
{% extends "base.html" %}

{% block content %}
<div class="row my-2">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header bg-primary">
                <h2 class="card-text text-light">My Profile:</h2>
            </div>
            <div class="card-body">
                <h4>Username: {{ object.username.capitalize}}</h4>
                {% if object.name %}
                <p>{{ object.anme }}</p>
                {% endif %}
                <hr>
                {% if object == request.user %}
                <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
                <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-mail</a>
                <a class="btn btn-primary" href="{% url 'users:subscription' request.user.username %}" role="button">My
                    Subscription</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <form action="{% url 'users:update' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form|crispy}}
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Update</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

src/templates/users/user_subscription.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header bg-dark text-light">
                <h5 class="card-title pt-2">Subscription Detail</h5>
            </div>
            <div class="card-body">
                <h4 class="card-text text-muted">Subscriber: {{ user.username }}</h4>
                <h4 class="card-text text-muted">Package: {{ user.subscription.pricing.name }}</h4>
                <h4 class="card-text text-muted">Status: {{ user.subscription.status }}</h4>
                <a class="btn btn-success" href="{% url 'payment:enroll' %}"><strong>Change your package</strong></a>
                <hr>
                <h4 class="card-text text-muted">Cancel Your membership: </h4>
                <p class="card-text">
                    Once you've cancelled membership, you will no longer access to all of the content on
                    mysite.com
                </p>
                {% if user.subscription.status != 'canceled' %}
                <form action="{% url 'users:cancel-subscription' request.user.username %}" method='POST'>
                    {% csrf_token %}
                    {{ form }}
                    <button class="btn btn-md btn-danger text-nuted" type="submit">Cancel Subscription</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock content %}