src/blog/urls.py
from django.urls import path
from.views import PostListView, PostDetailView, like_view


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('detail/<slug>', PostDetailView.as_view(), name='detail'),
    path('like/<slug>/', like_view, name='like')
]

src/content/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, VideoDetailView


app_name = 'content'

urlpatterns = [
    path('', CourseListView.as_view(), name='course-list'),
    path('course-detail/<slug>/', CourseDetailView.as_view(), name='course-detail'),
    path('video-detail/<slug>/<video_slug>/', VideoDetailView.as_view(), name='video-detail'),
]

src/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('content', include('content.urls', namespace='content')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/payment/urls.py
from django.urls import path
from .views import PaymentView, CreateSubscriptionView, RetryInvoiceView, EnrollView, webhook

app_name = 'payment'

urlpatterns = [
    path('enroll/', EnrollView.as_view(), name='enroll'),
    path('enroll/<slug>', PaymentView.as_view(), name='payment'),
    path('create-subscription/', CreateSubscriptionView.as_view(), name='create-subscription'),
    path('retry-invoice/', RetryInvoiceView.as_view(), name='retry-invoice'),
    path('webhook/', webhook, name='webhook')
]

src/templates/navbar/navbar.html
<nav class="navbar navbar-expand-lg navbar-success bg-success">
  <div class="container">
    <!-- <a class="navbar-brand" href="/">Navbar</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'blog:post-list' %}"><i class="fa fa-home"></i>Home</a>
      </div>
      {% if request.user.is_authenticated %}
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'content:course-list' %}">Courses</a>
        <a class="nav-link" href="{% url 'payment:enroll' %}">Enroll</a>
        <a class="nav-link" href="{% url 'users:detail' request.user.username %}">My
          Profile</a>
      </div>
      <div class="navbar-nav ml-auto">
        <a class="nav-link" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt"></i> Sign
          Out</a>
      </div>
      {% else %}
      <div class="navbar-nav ml-auto">
        <a class="nav-link" href="{% url 'account_login' %}"><i class="fas fa-sign-in-alt"></i> Sign In</a>
        <a class="nav-link" href="{% url 'account_signup' %}"><i class="fas fa-user-plus"></i> Sign Up</a>
      </div>
      {% endif %}
    </div>
  </div>
</nav>